name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    if: |
      contains(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
       - name: Checkout repository
         uses: actions/checkout@v6
         with:
           fetch-depth: 1
           persist-credentials: false

       - name: Run OpenCode
         uses: anomalyco/opencode/github@latest
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_BEARER_TOKEN_BEDROCK: ${{ secrets.AWS_BEARER_TOKEN_BEDROCK }}
            AWS_DEFAULT_REGION: eu-west-3
         with:
            model: "amazon-bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0"
            use_github_token: true
