name: opencode-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: anomalyco/opencode/github@v1.15.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_BEARER_TOKEN_BEDROCK: ${{ secrets.AWS_BEARER_TOKEN_BEDROCK }}
          AWS_DEFAULT_REGION: eu-west-3
        with:
          model: "amazon-bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0"
          use_github_token: true
          agent: monagent
          prompt: |
            Draw a cat
      - name: check opencode version
        run: |
          echo "OpenCode version: $(opencode --version)"
